name: Auxsome
favicon: null
layout_spectrum: 0.67903
typography_spectrum: 0.52504
title: 'A User Experience site, some of the time.  '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cccccc'
    - '#808080'
    - '#4d4d4d'
    - '#d61c59'
  brandStrength: 0.6024420787580311
  lightness: 0.5048829172737896
  saturation: 0.75
  rhythmicContrast: 0.3761259976308793
purpose: []
