name: Auxsome
favicon: null
layout_spectrum: 0.5032609207555652
typography_spectrum: 0.9338142478372902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6024420787580311
  lightness: 0.5048829172737896
  saturation: 0.891604756237939
  rhythmicContrast: 0.3761259976308793
purpose: []
